import React from "react";
const columns = [
    { name: "ID", uid: "id", sortable: true },
    { name: "NAME", uid: "name", sortable: true },
    { name: "COUNT", uid: "count", sortable: true },
    { name: "REQUESTED BY", uid: "requested by", sortable: true },
    { name: "TO", uid: "to", sortable: true },
    { name: "FROM", uid: "from", sortable: true },
    { name: "STATUS", uid: "status", sortable: true },
  
];

const statusOptions = [
    { name: "Good", uid: "good" },
    { name: "Lost", uid: "lost" },
    { name: "Damaged", uid: "Damage" },
  ];
const users = [
    {
        id: 1,
        name: "Arduino UNO R3",
        count: 5,
        "requested by": "Pema Dorji",
        to: "Tenzin",
        from: "Karma",
        status: "Lost",
      },
      {
        id: 2,
        name: "Network Switch",
        count: 8,
        "requested by": "Sonam",
        to: "Namgay",
        from: "Dorji",
        status: "Good",
      },
      {
        id: 3,
        name: "Server Rack",
        count: 3,
        "requested by": "Karma",
        to: "Tashi",
        from: "Sonam",
        status: "Damaged",
      },
      {
        id: 4,
        name: "Laptop",
        count: 12,
        "requested by": "Tenzin",
        to: "Karma",
        from: "Pema",
        status: "Good",
      },
      {
        id: 5,
        name: "Desktop Computer",
        count: 7,
        "requested by": "Namgay",
        to: "Pema",
        from: "Karma",
        status: "Lost",
      },
      {
        id: 6,
        name: "Printer",
        count: 9,
        "requested by": "Tashi",
        to: "Sonam",
        from: "Tenzin",
        status: "Good",
      },
      {
        id: 7,
        name: "Scanner",
        count: 2,
        "requested by": "Pema",
        to: "Karma",
        from: "Tenzin",
        status: "Lost",
      },
      {
        id: 8,
        name: "External Hard Drive",
        count: 6,
        "requested by": "Karma",
        to: "Tashi",
        from: "Sonam",
        status: "Damaged",
      },
      {
        id: 9,
        name: "RAM",
        count: 11,
        "requested by": "Sonam",
        to: "Pema",
        from: "Namgay",
        status: "Good",
      },
      {
        id: 10,
        name: "CPU",
        count: 4,
        "requested by": "Tenzin",
        to: "Karma",
        from: "Tashi",
        status: "Lost",
      },
      {
        id: 11,
        name: "GPU",
        count: 8,
        "requested by": "Namgay",
        to: "Pema",
        from: "Sonam",
        status: "Good",
      },
      {
        id: 12,
        name: "Motherboard",
        count: 3,
        "requested by": "Pema",
        to: "Karma",
        from: "Tenzin",
        status: "Lost",
      },
      {
        id: 13,
        name: "Monitor",
        count: 9,
        "requested by": "Tashi",
        to: "Sonam",
        from: "Pema",
        status: "Damaged",
      },
      {
        id: 14,
        name: "Keyboard",
        count: 6,
        "requested by": "Sonam",
        to: "Pema",
        from: "Karma",
        status: "Good",
      },
      {
        id: 15,
        name: "Mouse",
        count: 11,
        "requested by": "Namgay",
        to: "Karma",
        from: "Tashi",
        status: "Lost",
      },
    ];

export { columns, users, statusOptions };
