import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { fontSans } from "@/config/fonts";
import { useState } from "react";
import clsx from "clsx";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { Flip, ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { GlobalProvider } from "@/contex";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch("http://localhost:5000/auth/auth-user", {
    headers: {
      Cookie: `auth_session=${cookies().get("auth_session")?.value ?? ""}`,
    },
  });

  if (!res.ok) {
    console.log("resss", res)
    console.log("Failed to authorize user!");
    return redirect("/login");
  }
  const userId = res && (await res.json());

  return (
    <html lang="en">
      <body className={clsx("font-sans antialiased", fontSans.className)}>
        <GlobalProvider user={userId}>
          <Providers>
            {children}
            <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              transition={Flip}
            
            />
          </Providers>
        </GlobalProvider>
      </body>
    </html>
  );
}
